# Generated by Django 3.2.6 on 2022-04-03 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0024_auto_20210616_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucheritem',
            options={'ordering': ['-auto_timedate']},
        ),
        migrations.AlterModelOptions(
            name='vouchers',
            options={'ordering': ['-voucher_date']},
        ),
        migrations.AddField(
            model_name='vouchers',
            name='guid',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='crucialnumbers',
            name='auto_timedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 3, 9, 33, 40, 315728), null=True),
        ),
        migrations.AlterField(
            model_name='crucialnumbersbank',
            name='auto_timedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 3, 9, 33, 40, 316722), null=True),
        ),
    ]
